AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GoodBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - Id: GlacierRule
          Prefix: glacier
          Status: Enabled
          ExpirationInDays: '365'
          Transitions:
            - TransitionInDays: '1'
              StorageClass: Glacier
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      Tags:
        -
          Key: "Environment"
          Value: "test"
        -
          Key: "Role"
          Value: "test"
        -
          Key: "Owner"
          Value: "mike"
        -
          Key: "Name"
          Value: "s3-example"

  GoodBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "GoodBucket"
      PolicyDocument: !Sub |
        {
          "Id": "s3-secured-policy-arn:aws:s3:::${GoodBucket}",
          "Statement": [
            {
              "Sid": "DenyIncorrectEncryptionHeader",
              "Action": "s3:PutObject",
              "Effect": "Deny",
              "Resource": "arn:aws:s3:::${GoodBucket}/*",
              "Condition": { "StringNotEquals": { "s3:x-amz-server-side-encryption": "AES256" } },
              "Principal": { "AWS": "*"}
            },
            {
              "Sid": "DenyUnEncryptedObjectUploads",
              "Action": "s3:PutObject",
              "Effect": "Deny",
              "Resource": "arn:aws:s3:::${GoodBucket}/*",
              "Condition": { "Null": { "s3:x-amz-server-side-encryption": "true" } },
              "Principal": { "AWS": "*"}
            },
            {
              "Sid": "ForceSSLOnlyAccess",
              "Action": "s3:*",
              "Effect": "Deny",
              "Resource": "arn:aws:s3:::${GoodBucket}/*",
              "Condition": { "Bool": { "aws:SecureTransport": "false" } },
              "Principal": { "AWS": "*"}
            }
          ]
        }

Outputs:
  BucketName:
    Value: !Ref 'GoodBucket'
    Description: Name of the sample Amazon S3 bucket.
